/** Google Apps Script bound to a private Spreadsheet. Deploy as Web app: Execute as me, Access anyone. */
const SCHEMA={
  Orders:['order_id','created_at','customer_id','first_name','last_name','phone','telegram','subject','description','slides_count','pricing_id','pricing_name','total_amount','deposit_amount','remaining_amount','order_status','updated_at'],
  Customers:['customer_id','created_at','first_name','last_name','phone','telegram'],
  Payments:['payment_id','order_id','amount','tracking_number','payment_date','status','verified_at','note','created_at'],
  Deliveries:['delivery_id','order_id','file_id','file_name','mime_type','size_bytes','created_at','active'],
  Invoices:['invoice_id','order_id','invoice_number','created_at','total_amount','deposit_amount','remaining_amount','status'],
  Pricing:['pricing_id','name','price','description','features','active'],
  Portfolio:['portfolio_id','title','category','description','image_url','preview_urls','active'],
  Settings:['key','value'],
  Admins:['admin_id','username','password_hash','salt','active','created_at']
};
const PUBLIC_SETTINGS=['telegram_username','card_number','card_holder','contact_phone','site_title'];
const ORDER_STATUSES=['new','waiting_payment','payment_review','confirmed','in_progress','completed','cancelled'];
const MAX_DELIVERY_BYTES=10*1024*1024;
function now_(){return new Date().toISOString()}
function text_(v,max){return String(v===undefined||v===null?'':v).trim().slice(0,max||2000)}
function digits_(v){return String(v||'').replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c)))}
function phone_(v){const value=digits_(v).replace(/\D/g,'');return /^9\d{9}$/.test(value)?'0'+value:value}
function quote_(basePrice,slidesCount){const base=Number(basePrice),slides=Number(slidesCount);if(!Number.isSafeInteger(base)||base<0||!Number.isInteger(slides)||slides<1||slides>500)fail_('تعرفه یا تعداد اسلاید معتبر نیست.');const extraSlides=Math.max(0,slides-12),total=Math.round(base*(1+extraSlides/10));if(!Number.isSafeInteger(total))fail_('مبلغ سفارش معتبر نیست.');const deposit=Math.round(total*.2);return {base:base,slides:slides,extraSlides:extraSlides,total:total,deposit:deposit,remaining:total-deposit}}
function jalaliDate_(value){let raw=digits_(value).trim();const old=raw.match(/^(20\d{2})-(\d{2})-(\d{2})$/);if(old){const y=Number(old[1]),m=Number(old[2]),d=Number(old[3]),date=new Date(Date.UTC(y,m-1,d,12));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)fail_('تاریخ واریز معتبر نیست.');const parts=new Intl.DateTimeFormat('en-US-u-ca-persian',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const get=t=>parts.find(x=>x.type===t).value;raw=get('year')+'/'+get('month')+'/'+get('day')}const match=raw.match(/^(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})$/)||raw.match(/^(\d{4})(\d{2})(\d{2})$/);if(!match)fail_('تاریخ واریز را به صورت شمسی، سال/ماه/روز وارد کنید.');const year=Number(match[1]),month=Number(match[2]),day=Number(match[3]),leap=[1,5,9,13,17,22,26,30].indexOf(year%33)>=0,max=month<=6?31:month<=11?30:leap?30:29;if(year<1300||year>1500||month<1||month>12||day<1||day>max)fail_('تاریخ واریز شمسی معتبر نیست.');return year+'/'+String(month).padStart(2,'0')+'/'+String(day).padStart(2,'0')}

function fail_(m){throw new Error(m)}
function sheet_(name){const s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(name);if(!s)fail_('برگه '+name+' پیدا نشد. ابتدا setupSpreadsheet را اجرا کنید.');return s}
function records_(name){const values=sheet_(name).getDataRange().getValues();if(values.length<2)return [];const head=values[0].map(String);return values.slice(1).map((r,i)=>{if(!r.some(c=>c!==''&&c!==null))return null;const o={_row:i+2};head.forEach((h,j)=>o[h]=r[j] instanceof Date?r[j].toISOString():r[j]);return o}).filter(Boolean)}
function public_(r){const o=Object.assign({},r);delete o._row;return o}
function cell_(v){return typeof v==='string'&&/^[=+\-@]/.test(v)?'\''+v:v}
function append_(name,o){const s=sheet_(name);s.appendRow(SCHEMA[name].map(k=>o[k]===undefined?'':cell_(o[k])));if(name==='Payments')s.getRange(s.getLastRow(),5).setNumberFormat('@').setValue(String(o.payment_date));if((name==='Orders'||name==='Customers')&&o.phone)s.getRange(s.getLastRow(),SCHEMA[name].indexOf('phone')+1).setNumberFormat('@').setValue(String(o.phone));return o}
function update_(name,row,changes){const s=sheet_(name),head=SCHEMA[name],range=s.getRange(row,1,1,head.length),current=range.getValues()[0];head.forEach((k,i)=>{if(Object.prototype.hasOwnProperty.call(changes,k))current[i]=cell_(changes[k])});range.setValues([current])}
function find_(name,key,value){return records_(name).find(r=>String(r[key])===String(value))}
function bool_(v){return v===true||String(v).toLowerCase()==='true'||v===1}
function lock_(fn){const l=LockService.getScriptLock();l.waitLock(25000);try{return fn()}finally{l.releaseLock()}}
function id_(prefix,name,col){const year=new Date().getFullYear(),key='seq_'+prefix+'_'+year,p=PropertiesService.getScriptProperties();const re=new RegExp('^'+prefix+'-'+year+'-(\\d+)$');let max=Number(p.getProperty(key)||0);records_(name).forEach(r=>{const m=String(r[col]||'').match(re);if(m)max=Math.max(max,Number(m[1]))});p.setProperty(key,String(max+1));return prefix+'-'+year+'-'+String(max+1).padStart(4,'0')}
function uid_(prefix){return prefix+'-'+Utilities.getUuid().slice(0,12)}
function hash_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,v,Utilities.Charset.UTF_8).map(b=>('0'+(b&255).toString(16)).slice(-2)).join('')}
function eq_(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function admin_(token){if(!token||!CacheService.getScriptCache().get('session_'+token))fail_('نشست مدیریت معتبر نیست؛ دوباره وارد شوید.');return true}
function response_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return response_({success:true,data:{status:'ok',service:'slide-studio-api'}})}
function doPost(e){let body={};let result;try{body=JSON.parse(e.parameter&&e.parameter.payload||e.postData&&e.postData.contents||'{}');const data=dispatch_(body.action,body.data||{},body.token||'');result={success:true,data:data}}catch(err){result={success:false,message:err.message||'خطای نامشخص'}}if(e.parameter&&e.parameter.transport==='iframe')return iframeResponse_(result,body);return response_(result)}
function iframeResponse_(result,body){const origin=String(body.origin||'');if(!/^https:\/\/[a-z0-9.-]+(?::[0-9]+)?$/i.test(origin)&&origin!=='null')return HtmlService.createHtmlOutput('Invalid origin');const message=JSON.stringify({kind:'slide-studio-api',request_id:body.request_id,result:result}).replace(/</g,'\\u003c');const target=origin==='null'?'*':origin;return HtmlService.createHtmlOutput('<!doctype html><meta charset=\"utf-8\"><script>window.top.postMessage('+message+','+JSON.stringify(target)+');</script>').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function dispatch_(action,d,token){switch(action){
  case 'getCapabilities':return {pricing_version:2,jalali_payment_date:true,confirmed_writes:true,delivery_version:1};
  case 'getPricing':return getPricing_(d,token);
  case 'getPortfolio':return getPortfolio_(d,token);
  case 'getSettings':return getSettings_();
  case 'createOrder':return createOrder_(d);
  case 'getOrder':return getOrder_(d);
  case 'downloadDelivery':return downloadDelivery_(d);
  case 'submitPayment':return submitPayment_(d);
  case 'getInvoice':return getInvoice_(d);
  case 'login':return login_(d);
  case 'logout':admin_(token);CacheService.getScriptCache().remove('session_'+token);return {logged_out:true};
  case 'dashboard':admin_(token);return dashboard_();
  case 'getOrders':admin_(token);return records_('Orders').map(public_).reverse();
  case 'getDeliveries':admin_(token);return getDeliveries_(d);
  case 'uploadDelivery':admin_(token);return uploadDelivery_(d);
  case 'removeDelivery':admin_(token);return removeDelivery_(d);
  case 'updateOrderStatus':admin_(token);return updateOrderStatus_(d);
  case 'getPayments':admin_(token);return getPayments_();
  case 'approvePayment':admin_(token);return approvePayment_(d);
  case 'rejectPayment':admin_(token);return rejectPayment_(d);
  case 'getCustomers':admin_(token);return getCustomers_();
  case 'getInvoices':admin_(token);return getInvoices_();
  case 'updatePricing':admin_(token);return updatePricing_(d);
  case 'addPortfolio':admin_(token);return addPortfolio_(d);
  case 'updatePortfolio':admin_(token);return updatePortfolio_(d);
  case 'deletePortfolio':admin_(token);return deletePortfolio_(d);
  case 'updateSettings':admin_(token);return updateSettings_(d);
  default:fail_('عملیات نامعتبر است.')
}}
function setupSpreadsheet(){const ss=SpreadsheetApp.getActiveSpreadsheet();Object.keys(SCHEMA).forEach(name=>{let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);const head=SCHEMA[name];if(s.getLastRow()===0){s.appendRow(head);s.setFrozenRows(1);s.getRange(1,1,1,head.length).setFontWeight('bold').setBackground('#29243f').setFontColor('#ffffff')}else{const actual=s.getRange(1,1,1,head.length).getValues()[0].map(String);if(head.some((h,i)=>actual[i]!==h))fail_('سرستون‌های برگه '+name+' با نسخهٔ فعلی سازگار نیستند.')}});if(records_('Pricing').length===0){[
  {pricing_id:'simple',name:'ساده',price:360000,description:'بدون عکس و تصویر خاص و با طراحی ساده.',features:'چیدمان منظم • طراحی ساده',active:true},
  {pricing_id:'pro',name:'حرفه‌ای',price:480000,description:'با تعداد محدود تصویر و افکت‌های ساده.',features:'تصاویر محدود • افکت ساده',active:true},
  {pricing_id:'motion',name:'انیمیشنی',price:780000,description:'با تصاویر آماده از اینترنت و انیمیشن‌های بیشتر.',features:'تصاویر آماده • انیمیشن بیشتر',active:true},
  {pricing_id:'custom',name:'گرافیکی و اختصاصی',price:840000,description:'ساخت تصاویر اختصاصی و طراحی تم اختصاصی پاورپوینت.',features:'تم اختصاصی • تصویرسازی',active:true}
].forEach(x=>append_('Pricing',x))}const keys={telegram_username:'',card_number:'',card_holder:'',contact_phone:'',site_title:'استودیو اسلاید'};Object.keys(keys).forEach(k=>{if(!find_('Settings','key',k))append_('Settings',{key:k,value:keys[k]})});return 'Setup complete'}
function setupAdmin(){const p=PropertiesService.getScriptProperties(),username=text_(p.getProperty('BOOTSTRAP_ADMIN_USERNAME'),80),password=String(p.getProperty('BOOTSTRAP_ADMIN_PASSWORD')||'');if(!username||password.length<12)fail_('نام کاربری و رمز حداقل ۱۲ کاراکتری را در Script Properties ثبت کنید.');if(find_('Admins','username',username))fail_('این نام کاربری از قبل وجود دارد.');const salt=Utilities.getUuid()+Utilities.getUuid();append_('Admins',{admin_id:uid_('ADM'),username:username,password_hash:hash_(salt+password),salt:salt,active:true,created_at:now_()});p.deleteProperty('BOOTSTRAP_ADMIN_USERNAME');p.deleteProperty('BOOTSTRAP_ADMIN_PASSWORD');return 'Admin created'}
function setupDeliveryStorage(){setupSpreadsheet();const p=PropertiesService.getScriptProperties();let id=p.getProperty('DELIVERY_FOLDER_ID');if(!id){id=DriveApp.createFolder('PPT Studio Deliveries').getId();p.setProperty('DELIVERY_FOLDER_ID',id)}else DriveApp.getFolderById(id);return 'Delivery storage ready: '+id}
function login_(d){const username=text_(d.username,80),password=String(d.password||''),cache=CacheService.getScriptCache(),key='attempt_'+hash_(username).slice(0,24),attempts=Number(cache.get(key)||0);if(attempts>=5)fail_('ورود موقتاً محدود شده است. ۱۵ دقیقه دیگر تلاش کنید.');const a=find_('Admins','username',username);if(!a||!bool_(a.active)||!eq_(hash_(String(a.salt)+password),String(a.password_hash))){cache.put(key,String(attempts+1),900);fail_('نام کاربری یا رمز عبور نادرست است.')}cache.remove(key);const token=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');cache.put('session_'+token,String(a.admin_id),21600);return {token:token,expires_in:21600}}
function getPricing_(d,token){let rows=records_('Pricing');if(d.include_inactive){admin_(token)}else rows=rows.filter(r=>bool_(r.active));return rows.map(public_)}
function getPortfolio_(d,token){let rows=records_('Portfolio');if(d.include_inactive){admin_(token)}else rows=rows.filter(r=>bool_(r.active));return rows.map(public_)}
function getSettings_(){const out={};records_('Settings').forEach(r=>{if(PUBLIC_SETTINGS.indexOf(r.key)>=0)out[r.key]=r.value});return out}
function createOrder_(d){if(Number(d.quote_version)!==2)fail_('نسخهٔ سایت قدیمی است؛ صفحه را بازخوانی کنید.');const first=text_(d.first_name,60),last=text_(d.last_name,60),phone=phone_(d.phone),subject=text_(d.subject,160),slides=Number(d.slides_count),pid=text_(d.pricing_id,80);if(!first||!last||!/^09\d{9}$/.test(phone)||!subject||!Number.isInteger(slides)||slides<1||slides>500)fail_('اطلاعات سفارش معتبر نیست.');return lock_(()=>{const p=find_('Pricing','pricing_id',pid);if(!p||!bool_(p.active))fail_('تعرفهٔ انتخابی در دسترس نیست.');const quote=quote_(p.price,slides);let c=records_('Customers').find(r=>phone_(r.phone)===phone);if(!c){c={customer_id:uid_('CUS'),created_at:now_(),first_name:first,last_name:last,phone:phone,telegram:text_(d.telegram,80)};append_('Customers',c)}else update_('Customers',c._row,{first_name:first,last_name:last,telegram:text_(d.telegram,80)});const id=id_('ORD','Orders','order_id');append_('Orders',{order_id:id,created_at:now_(),customer_id:c.customer_id,first_name:first,last_name:last,phone:phone,telegram:text_(d.telegram,80),subject:subject,description:text_(d.description,2000),slides_count:slides,pricing_id:pid,pricing_name:p.name,total_amount:quote.total,deposit_amount:quote.deposit,remaining_amount:quote.remaining,order_status:'waiting_payment',updated_at:now_()});SpreadsheetApp.flush();const saved=find_('Orders','order_id',id);if(!saved||Number(saved.total_amount)!==quote.total||Number(saved.slides_count)!==slides||phone_(saved.phone)!==phone)fail_('ثبت سفارش در Google Sheets تأیید نشد.');return {order_id:id,total_amount:quote.total,deposit_amount:quote.deposit,remaining_amount:quote.remaining,slides_count:slides,phone:phone}})}
function verifiedOrder_(d){const id=text_(d.order_id,40).toUpperCase(),phone=phone_(d.phone);const o=find_('Orders','order_id',id);if(!o||!phone||phone_(o.phone)!==phone)fail_('سفارشی با این شماره و شماره تماس پیدا نشد.');return o}
function paymentLabel_(s){return {pending:'در انتظار بررسی',approved:'تأیید شده',rejected:'رد شده'}[s]||'هنوز ثبت نشده'}
function deliveryRows_(){return SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Deliveries')?records_('Deliveries'):[]}
function deliveryMeta_(r){return {delivery_id:r.delivery_id,file_name:r.file_name,size_bytes:Number(r.size_bytes),created_at:r.created_at}}
function getDeliveries_(d){const id=text_(d.order_id,40).toUpperCase();if(!find_('Orders','order_id',id))fail_('سفارش پیدا نشد.');return deliveryRows_().filter(r=>r.order_id===id&&bool_(r.active)).map(deliveryMeta_)}
function uploadDelivery_(d){const id=text_(d.order_id,40).toUpperCase(),name=text_(d.file_name,180).replace(/[\\/\r\n]/g,'_'),ext=(name.match(/\.(pptx|ppt)$/i)||[])[1],raw=String(d.content_base64||'');if(!find_('Orders','order_id',id))fail_('سفارش پیدا نشد.');if(!ext)fail_('فقط فایل pptx یا ppt مجاز است.');if(!raw||raw.length>Math.ceil(MAX_DELIVERY_BYTES/3)*4+4||!/^[A-Za-z0-9+/]+={0,2}$/.test(raw))fail_('فایل معتبر نیست یا حجم آن از ۱۰ مگابایت بیشتر است.');const folderId=PropertiesService.getScriptProperties().getProperty('DELIVERY_FOLDER_ID');if(!folderId||!SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Deliveries'))fail_('ابتدا setupDeliveryStorage را در Apps Script اجرا کنید.');const bytes=Utilities.base64Decode(raw),head=bytes.slice(0,8).map(x=>x&255),pptx=ext.toLowerCase()==='pptx',valid=pptx?head[0]===80&&head[1]===75&&head[2]===3&&head[3]===4:head.join(',')==='208,207,17,224,161,177,26,225';if(!valid||bytes.length===0||bytes.length>MAX_DELIVERY_BYTES)fail_('محتوای فایل پاورپوینت معتبر نیست یا حجم آن از ۱۰ مگابایت بیشتر است.');const mime=pptx?'application/vnd.openxmlformats-officedocument.presentationml.presentation':'application/vnd.ms-powerpoint';return lock_(()=>{const file=DriveApp.getFolderById(folderId).createFile(Utilities.newBlob(bytes,mime,name)),entry={delivery_id:uid_('DLV'),order_id:id,file_id:file.getId(),file_name:name,mime_type:mime,size_bytes:bytes.length,created_at:now_(),active:true};append_('Deliveries',entry);SpreadsheetApp.flush();const saved=find_('Deliveries','delivery_id',entry.delivery_id);if(!saved||saved.file_id!==entry.file_id)fail_('ثبت فایل در Google Sheets تأیید نشد.');return deliveryMeta_(entry)})}
function removeDelivery_(d){const id=text_(d.delivery_id,80);return lock_(()=>{const entry=find_('Deliveries','delivery_id',id);if(!entry||!bool_(entry.active))fail_('فایل تحویل پیدا نشد.');const o=find_('Orders','order_id',entry.order_id);if(o&&o.order_status==='completed'&&deliveryRows_().filter(r=>r.order_id===o.order_id&&bool_(r.active)).length<=1)fail_('برای برداشتن آخرین فایل، ابتدا وضعیت سفارش را از «تکمیل شده» تغییر دهید.');update_('Deliveries',entry._row,{active:false});SpreadsheetApp.flush();return {delivery_id:id,removed:true}})}
function downloadDelivery_(d){const o=verifiedOrder_(d);if(o.order_status!=='completed')fail_('فایل پس از تکمیل سفارش در دسترس است.');const id=text_(d.delivery_id,80),entry=deliveryRows_().find(r=>r.delivery_id===id&&r.order_id===o.order_id&&bool_(r.active));if(!entry)fail_('فایل سفارش پیدا نشد.');const file=DriveApp.getFileById(String(entry.file_id));if(file.getSize()>MAX_DELIVERY_BYTES)fail_('حجم فایل بیش از حد مجاز است.');return {file_name:entry.file_name,mime_type:entry.mime_type,content_base64:Utilities.base64Encode(file.getBlob().getBytes())}}
function getOrder_(d){const o=verifiedOrder_(d),payments=records_('Payments').filter(p=>p.order_id===o.order_id),latest=payments[payments.length-1],inv=find_('Invoices','order_id',o.order_id),deliveries=o.order_status==='completed'?deliveryRows_().filter(r=>r.order_id===o.order_id&&bool_(r.active)).map(deliveryMeta_):[];return {order_id:o.order_id,created_at:o.created_at,subject:o.subject,pricing_name:o.pricing_name,total_amount:o.total_amount,deposit_amount:o.deposit_amount,remaining_amount:o.remaining_amount,slides_count:o.slides_count,order_status:o.order_status,payment_status_label:paymentLabel_(latest&&latest.status),invoice_number:inv&&inv.invoice_number||'',deliveries:deliveries}}
function submitPayment_(d){const tracking=text_(d.tracking_number,100),date=jalaliDate_(d.payment_date);if(!tracking)fail_('شماره پیگیری پرداخت را وارد کنید.');return lock_(()=>{const o=verifiedOrder_(d);if(o.order_status==='cancelled')fail_('این سفارش لغو شده است.');const prev=records_('Payments').filter(p=>p.order_id===o.order_id),latest=prev[prev.length-1];if(latest&&latest.status==='pending')fail_('پرداخت قبلی در انتظار بررسی است.');if(latest&&latest.status==='approved')fail_('پرداخت این سفارش قبلاً تأیید شده است.');const id=uid_('PAY');append_('Payments',{payment_id:id,order_id:o.order_id,amount:o.deposit_amount,tracking_number:tracking,payment_date:date,status:'pending',verified_at:'',note:text_(d.note,500),created_at:now_()});update_('Orders',o._row,{order_status:'payment_review',updated_at:now_()});SpreadsheetApp.flush();const saved=find_('Payments','payment_id',id);if(!saved||String(saved.payment_date)!==date)fail_('ثبت پرداخت در Google Sheets تأیید نشد.');return {payment_id:id,status:'pending',payment_date:date}})}
function getInvoice_(d){const o=verifiedOrder_(d),i=find_('Invoices','order_id',o.order_id);if(!i)fail_('فاکتور هنوز صادر نشده است.');return {invoice_number:i.invoice_number,order_id:o.order_id,customer_name:o.first_name+' '+o.last_name,subject:o.subject,pricing_name:o.pricing_name,total_amount:i.total_amount,deposit_amount:i.deposit_amount,remaining_amount:i.remaining_amount,created_at:i.created_at,status:i.status}}
function updateOrderStatus_(d){const id=text_(d.order_id,40),s=text_(d.status,30);if(ORDER_STATUSES.indexOf(s)<0)fail_('وضعیت سفارش نامعتبر است.');return lock_(()=>{const o=find_('Orders','order_id',id);if(!o)fail_('سفارش پیدا نشد.');if(['confirmed','in_progress','completed'].indexOf(s)>=0&&!records_('Payments').some(p=>p.order_id===id&&p.status==='approved'))fail_('برای این وضعیت، پرداخت باید تأیید شده باشد.');if(s==='completed'&&!deliveryRows_().some(r=>r.order_id===id&&bool_(r.active)))fail_('برای تکمیل سفارش، ابتدا فایل پاورپوینت را بارگذاری کنید.');update_('Orders',o._row,{order_status:s,updated_at:now_()});return {order_id:id,status:s}})}
function getPayments_(){const orders=records_('Orders'),byId={};orders.forEach(o=>byId[o.order_id]=o);return records_('Payments').reverse().map(p=>Object.assign(public_(p),{customer_name:byId[p.order_id]?byId[p.order_id].first_name+' '+byId[p.order_id].last_name:''}))}
function approvePayment_(d){return lock_(()=>{const p=find_('Payments','payment_id',text_(d.payment_id,80));if(!p||p.status!=='pending')fail_('پرداخت قابل تأیید نیست.');const o=find_('Orders','order_id',p.order_id);if(!o||o.order_status==='cancelled')fail_('سفارش معتبر نیست.');update_('Payments',p._row,{status:'approved',verified_at:now_()});update_('Orders',o._row,{order_status:'confirmed',updated_at:now_()});let i=find_('Invoices','order_id',o.order_id);if(!i){i={invoice_id:uid_('INV'),order_id:o.order_id,invoice_number:id_('INV','Invoices','invoice_number'),created_at:now_(),total_amount:o.total_amount,deposit_amount:o.deposit_amount,remaining_amount:o.remaining_amount,status:'approved'};append_('Invoices',i)}return {order_id:o.order_id,invoice_number:i.invoice_number,status:'approved'}})}
function rejectPayment_(d){return lock_(()=>{const p=find_('Payments','payment_id',text_(d.payment_id,80));if(!p||p.status!=='pending')fail_('پرداخت قابل رد نیست.');const o=find_('Orders','order_id',p.order_id);update_('Payments',p._row,{status:'rejected',verified_at:now_()});if(o)update_('Orders',o._row,{order_status:'waiting_payment',updated_at:now_()});return {payment_id:p.payment_id,status:'rejected'}})}
function getCustomers_(){const orders=records_('Orders');return records_('Customers').map(c=>{const own=orders.filter(o=>o.customer_id===c.customer_id),paid=own.filter(o=>['confirmed','in_progress','completed'].indexOf(o.order_status)>=0);return Object.assign(public_(c),{order_count:own.length,total_spent:paid.reduce((n,o)=>n+Number(o.total_amount||0),0),last_order:own.length?own[own.length-1].created_at:''})})}
function getInvoices_(){const orders=records_('Orders'),map={};orders.forEach(o=>map[o.order_id]=o);return records_('Invoices').reverse().map(i=>Object.assign(public_(i),{customer_name:map[i.order_id]?map[i.order_id].first_name+' '+map[i.order_id].last_name:'',subject:map[i.order_id]?map[i.order_id].subject:'',pricing_name:map[i.order_id]?map[i.order_id].pricing_name:''}))}
function dashboard_(){const orders=records_('Orders'),payments=records_('Payments'),approved=payments.filter(p=>p.status==='approved'),month=now_().slice(0,7);const count=s=>orders.filter(o=>o.order_status===s).length;return {new_orders:orders.filter(o=>String(o.created_at).slice(0,10)===now_().slice(0,10)).length,waiting_payment:count('waiting_payment'),payment_review:count('payment_review'),in_progress:count('in_progress'),completed:count('completed'),total_revenue:approved.reduce((n,p)=>n+Number(p.amount||0),0),month_revenue:approved.filter(p=>String(p.verified_at).slice(0,7)===month).reduce((n,p)=>n+Number(p.amount||0),0),latest_orders:orders.slice(-8).reverse().map(public_)}}
function updatePricing_(d){const p=find_('Pricing','pricing_id',text_(d.pricing_id,80)),price=Number(d.price);if(!p)fail_('تعرفه پیدا نشد.');if(!text_(d.name,100)||!Number.isSafeInteger(price)||price<0)fail_('نام یا مبلغ تعرفه معتبر نیست.');update_('Pricing',p._row,{name:text_(d.name,100),price:price,description:text_(d.description,500),features:text_(d.features,500),active:bool_(d.active)});return {pricing_id:p.pricing_id}}
function url_(v){const s=text_(v,500);if(s&&!/^https:\/\//i.test(s))fail_('نشانی تصویر باید با https:// شروع شود.');return s}
function portfolioData_(d){const title=text_(d.title,120),category=text_(d.category,80);if(!title||!category)fail_('عنوان و دسته‌بندی لازم هستند.');return {title:title,category:category,description:text_(d.description,700),image_url:url_(d.image_url),preview_urls:text_(d.preview_urls,2000),active:bool_(d.active)}}
function addPortfolio_(d){const item=Object.assign({portfolio_id:uid_('PORT')},portfolioData_(d));append_('Portfolio',item);return {portfolio_id:item.portfolio_id}}
function updatePortfolio_(d){const p=find_('Portfolio','portfolio_id',text_(d.portfolio_id,80));if(!p)fail_('نمونه‌کار پیدا نشد.');update_('Portfolio',p._row,portfolioData_(d));return {portfolio_id:p.portfolio_id}}
function deletePortfolio_(d){const p=find_('Portfolio','portfolio_id',text_(d.portfolio_id,80));if(!p)fail_('نمونه‌کار پیدا نشد.');sheet_('Portfolio').deleteRow(p._row);return {deleted:true}}
function updateSettings_(d){PUBLIC_SETTINGS.forEach(k=>{if(!Object.prototype.hasOwnProperty.call(d,k))return;let value=text_(d[k],200);if(k==='card_number')value=digits_(value).replace(/[^0-9]/g,'');if(k==='telegram_username')value=value.replace(/^@/,'');const s=find_('Settings','key',k);if(s)update_('Settings',s._row,{value:value});else append_('Settings',{key:k,value:value})});return getSettings_()}
